add YandexMapKit support
hulab/ClusterKit pull request #62
Opened 2019-01-24 13:30 UTC by petropavel13

2019-01-24 13:43 UTC, Viveron approved these changes

2019-01-24 20:00 UTC, maxep requested changes
Thank you very much @petropavel13 ! this is an awesome contribution and it is very well implemented!
I've some comments following my review.

2019-01-24 20:00 UTC, maxep commented on ClusterKit.podspec
> +  s.subspec 'YandexMapKit' do |ss|
Like `GoogleMaps` sdk (https://github.com/googlemaps/google-maps-ios-utils/issues/23) `YandexMapKit` is statically built, which mean we can't use them as subspec dependency yet. Better to keep both `GoogleMaps` and `YandexMapKit` commented until both of them are dynamically built!

2019-01-24 20:00 UTC, maxep commented on ClusterKit.podspec
> +    ss.dependency 'Mapbox-iOS-SDK', '~> 4.7'
Better keep that for another PR.

2019-01-24 20:00 UTC, maxep commented on ClusterKit/YandexMapKit/YMKMapView+ClusterKit.m
> +        [self.delegate selectPlacemark:placemark
Should check if delegate respond to selector.

2019-01-24 20:00 UTC, maxep commented on ClusterKit/YandexMapKit/YMKMapView+ClusterKit.m
> +        [self.delegate deselectPlacemark:placemark
Should check if delegate respond to selector.

2019-01-24 20:00 UTC, maxep commented on Examples/Example-swift/YandexMapViewController.swift
> +        // workaround (https://github.com/yandex/mapkit-ios-demo/issues/23)
Good to know!

2019-01-24 20:00 UTC, maxep commented on ClusterKit/YandexMapKit/YMKMapView+ClusterKit.m
> +        // actually, it didn't work (https://github.com/yandex/mapkit-ios-demo/issues/21)
So animations are not yet supported on `YandexMapKit`?

2019-01-24 20:00 UTC, maxep commented on ClusterKit/YandexMapKit/YMKMapView+ClusterKit.h
> +@protocol YMKMapViewDelegate <NSObject>
I don't really see the point of having `YMKMapViewDelegate` to manage selection/deselection as this should be handled by the `YMKMapObjectTapListener`. Is there a particular use case that you are thinking of?

2019-01-25 08:54 UTC, petropavel13 commented on ClusterKit.podspec
> +  s.subspec 'YandexMapKit' do |ss|
got it. thanks!
will add your comment to podspec to clarify the problem for everyone else

2019-01-25 08:58 UTC, petropavel13 commented on ClusterKit/YandexMapKit/YMKMapView+ClusterKit.m
> +        [self.delegate selectPlacemark:placemark
Can you explain why?

There is a protocol with non-optional requirements:
```objc
@protocol YMKMapViewDelegate <NSObject>

- (void)selectPlacemark:(YMKPlacemarkMapObject *)placemark
             forCluster:(CKCluster *)cluster
               animated:(BOOL)animated;

- (void)deselectPlacemark:(YMKPlacemarkMapObject *)placemark
               forCluster:(CKCluster *)cluster
                 animated:(BOOL)animated;

@end
```

and delegate object that conforms it:
```objc
@property(nonatomic, weak) IBOutlet id<YMKMapViewDelegate> delegate;
```

it gives us, at least, compile-time safety, isn't it?

2019-01-25 09:01 UTC, petropavel13 commented on ClusterKit/YandexMapKit/YMKMapView+ClusterKit.m
> +        // actually, it didn't work (https://github.com/yandex/mapkit-ios-demo/issues/21)
apparently yes :/
or I don't know how to make it work

2019-01-25 09:09 UTC, petropavel13 commented on ClusterKit/YandexMapKit/YMKMapView+ClusterKit.h
> +@protocol YMKMapViewDelegate <NSObject>
Agree. No. Maybe there will be a particular case, so I implemented that in advance.
I'll remove this delegate.

2019-01-25 09:14 UTC, petropavel13 commented
Thanks for quick answer and code review!

2019-01-25 14:05 UTC, maxep commented on ClusterKit/YandexMapKit/YMKMapView+ClusterKit.m
> +        [self.delegate selectPlacemark:placemark
Yes you right, my bad!

2019-01-25 14:13 UTC, maxep commented on ClusterKit/YandexMapKit/YMKMapView+ClusterKit.m
> +        // actually, it didn't work (https://github.com/yandex/mapkit-ios-demo/issues/21)
Hopefully, that's gonna be available in a near future!

2019-01-25 14:15 UTC, maxep approved these changes
Thanks for the quick update, this all looks good to me! thanks again for that contribution

2019-01-25 14:16 UTC, merged